"""record which phrasing variant the composer chose

The composer has always picked one, deterministically from the lead id, so the
same lead has always received the same phrasing however many times the pipeline
retried. The assignment was real. The attribution was not: nothing wrote the
choice down, so no comparison between variants was possible however much mail
went out.

That is the whole of what an experiment framework needs and did not have. With
the column, arms can be compared; without it, "test send times and sequence
styles and promote winners" is a sentence about data that does not exist.

Nullable, and nothing is backfilled. The register a past draft used could be
recomputed from the lead id -- the picker is a stable hash -- but only while the
register list stays the same length, and it is a list somebody will add to. A
recomputed variant would silently start describing a different sentence than the
one that was sent, which is worse than an honest null.

Revision ID: 5d0a83f7c419
Revises: b291a9ca20db
Create Date: 2026-08-15 12:56:00.000000+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "be758247a3ba"
down_revision: str | None = "b291a9ca20db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message_drafts", sa.Column("variant", sa.String(length=40), nullable=True)
    )
    op.create_index(
        op.f("ix_message_drafts_variant"), "message_drafts", ["variant"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_drafts_variant"), table_name="message_drafts")
    op.drop_column("message_drafts", "variant")
    # ### end Alembic commands ###
