"""record when a message landed in the recipient's day

Every send timestamp Titan holds is UTC, which answers what time it was here and
nothing about what time it was for the person receiving it. So "which local hours
and weekdays produce replies" could not be asked of the data at all -- not
answered badly, not answered with low confidence: not asked.

**Derived, and not derivable later.** The obvious objection is that the local
hour is a function of ``sent_at`` and the recipient's timezone, so a query could
work it out whenever it liked. It could not. The clock a send was scheduled
against depends on the recipient's own timezone, the band their address falls
in, and the campaign's declared market, and all three can change after the fact
-- a business moves, a location is re-resolved, a campaign is re-pointed. A query
run next month would be answering with today's geography about last month's
send, confidently and wrongly.

``sent_timezone`` is stored alongside for the same reason: a reader needs to be
able to tell a London nine o'clock from a Los Angeles one, and the zone that was
used is the only thing that says which it was.

**Nothing is backfilled.** Existing rows keep NULL, which reads as "sent before
this was recorded". Computing a local hour for them now would be exactly the
mistake described above, dressed as data recovery -- and the learning module
treats a null slot as absent rather than as midnight, so the gap is honest
rather than a thousand messages appearing to have been sent at 00:00.

The index is partial. Only sent messages have a local hour and they are a small
minority of the table.

Revision ID: b7e3f95c1a28
Revises: 0c446bb50453
Create Date: 2026-08-15 12:10:00.000000+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b291a9ca20db"
down_revision: str | None = "0c446bb50453"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "campaign_policies",
        "send_days",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    op.add_column("messages", sa.Column("local_sent_hour", sa.Integer(), nullable=True))
    op.add_column(
        "messages", sa.Column("local_sent_weekday", sa.Integer(), nullable=True)
    )
    op.add_column(
        "messages", sa.Column("sent_timezone", sa.String(length=64), nullable=True)
    )
    op.create_index(
        "ix_messages_local_slot",
        "messages",
        ["workspace_id", "campaign_id", "local_sent_weekday", "local_sent_hour"],
        unique=False,
        postgresql_where=sa.text("local_sent_hour IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_messages_local_slot",
        table_name="messages",
        postgresql_where=sa.text("local_sent_hour IS NOT NULL"),
    )
    op.drop_column("messages", "sent_timezone")
    op.drop_column("messages", "local_sent_weekday")
    op.drop_column("messages", "local_sent_hour")
    op.alter_column(
        "campaign_policies",
        "send_days",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'[0, 1, 2, 3, 4]'::jsonb"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
