"""record what the campaign manager does, and give it two numbers to do it with

Bounded autonomy is easy to write down and hard to mean. This migration is the
part that means it.

**The manager gets its own columns.** ``daily_send_limit`` and
``min_lead_score`` are the human's numbers and they stay untouched, because they
are the bound every managed value is clamped against. Writing to them directly
would make next cycle's ceiling the manager's own previous answer, leaving
nothing to measure drift against -- a small persistent error would ratchet with
no anchor. Null in the managed columns means the manager has no opinion.

The pair resolve asymmetrically, and the asymmetry is the whole safety property:
the effective limit is the *lower* of the two, the effective score the *higher*.
A managed value can therefore only ever be more conservative than what a human
approved. There is no arrangement of these columns that sends more mail, or
mails worse leads, than the configuration allows.

**``autonomy_decisions`` records the refusals too.** A proposal the bounds
clamped is the most interesting row in the table: the manager reaching for
something and the boundary holding, which is the only direct evidence the
boundary works. Storing only what was applied would leave exactly the events
worth auditing unrecorded.

It is append-only, so it gets the same UPDATE trigger every other immutable
table has -- the ORM guard is not the only defence, and an audit trail that can
be edited is not one. And it is workspace-scoped, so it gets row-level security
here rather than in a later repair migration; ``c7d15e93f8a2`` exists because
that was once left out.

Revision ID: 4e91c7a2f8b6
Revises: 8c4d7e2b91f5
Create Date: 2026-08-15 11:33:00.000000+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0c446bb50453"
down_revision: str | None = "8c4d7e2b91f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_ISOLATION = (
    "  current_setting('titan.workspace_id', true) IS NULL"
    "  OR current_setting('titan.workspace_id', true) = ''"
    "  OR workspace_id = current_setting('titan.workspace_id', true)::uuid"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "autonomy_decisions",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actuation", sa.String(length=40), nullable=False),
        sa.Column("health", sa.String(length=20), nullable=False),
        sa.Column("previous_value", sa.Integer(), nullable=True),
        sa.Column("proposed_value", sa.Integer(), nullable=True),
        sa.Column("applied_value", sa.Integer(), nullable=True),
        sa.Column("applied", sa.Boolean(), nullable=False),
        sa.Column("refusal", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_autonomy_decisions_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_autonomy_decisions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_autonomy_decisions")),
    )
    op.create_index(
        op.f("ix_autonomy_decisions_actuation"),
        "autonomy_decisions",
        ["actuation"],
        unique=False,
    )
    op.create_index(
        "ix_autonomy_decisions_campaign",
        "autonomy_decisions",
        ["workspace_id", "campaign_id", "decided_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_autonomy_decisions_campaign_id"),
        "autonomy_decisions",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_autonomy_decisions_workspace_id"),
        "autonomy_decisions",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_autonomy_decisions_ws_created",
        "autonomy_decisions",
        ["workspace_id", "created_at"],
        unique=False,
    )
    op.add_column(
        "campaign_policies",
        sa.Column("managed_daily_send_limit", sa.Integer(), nullable=True),
    )
    op.add_column(
        "campaign_policies",
        sa.Column("managed_min_lead_score", sa.Integer(), nullable=True),
    )

    op.execute('ALTER TABLE "autonomy_decisions" ENABLE ROW LEVEL SECURITY')
    op.execute(
        'CREATE POLICY autonomy_decisions_workspace_isolation ON "autonomy_decisions" '
        f"USING ({_ISOLATION}) WITH CHECK ({_ISOLATION})"
    )
    op.execute(
        "CREATE TRIGGER autonomy_decisions_no_update "
        'BEFORE UPDATE ON "autonomy_decisions" FOR EACH ROW '
        "EXECUTE FUNCTION titan_forbid_mutation()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute(
        'DROP TRIGGER IF EXISTS autonomy_decisions_no_update ON "autonomy_decisions"'
    )
    op.execute(
        "DROP POLICY IF EXISTS autonomy_decisions_workspace_isolation "
        'ON "autonomy_decisions"'
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "campaign_policies",
        "send_days",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        server_default=sa.text("'[0, 1, 2, 3, 4]'::jsonb"),
        existing_nullable=False,
    )
    op.drop_column("campaign_policies", "managed_min_lead_score")
    op.drop_column("campaign_policies", "managed_daily_send_limit")
    op.drop_index("ix_autonomy_decisions_ws_created", table_name="autonomy_decisions")
    op.drop_index(
        op.f("ix_autonomy_decisions_workspace_id"), table_name="autonomy_decisions"
    )
    op.drop_index(
        op.f("ix_autonomy_decisions_campaign_id"), table_name="autonomy_decisions"
    )
    op.drop_index("ix_autonomy_decisions_campaign", table_name="autonomy_decisions")
    op.drop_index(
        op.f("ix_autonomy_decisions_actuation"), table_name="autonomy_decisions"
    )
    op.drop_table("autonomy_decisions")
    # ### end Alembic commands ###
