"""Classifying an inbound email.

Mission section 14. ``record_reply()`` and ``suppress()`` already existed and
already did the right thing; what was missing was deciding *which* of them an
arriving message warrants. Until now a human had to make that call by hand, so
invariant 15 protected only leads somebody remembered to enter.

The classification that matters most is **auto-reply versus human reply**, and
both errors are expensive in opposite directions:

* Treat an out-of-office as a reply and the sequence stops permanently. The
  lead was interested, nobody was there that week, and Titan never writes
  again.
* Treat a human reply as an auto-reply and Titan keeps mailing somebody who
  already answered -- the single rudest thing an outreach system can do, and
  the fastest route to a spam complaint.

So the auto-reply rules key on *headers first* (RFC 3834 and the de-facto
``Precedence``/``X-Auto*`` family), which mail systems set deliberately and
which a human message does not carry. Subject wording is only a fallback, and
never on its own enough to override a header that says otherwise.

Pure, no I/O: the caller decides what to persist.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import StrEnum


class ReplyKind(StrEnum):
    #: A person wrote back. Stops the sequence permanently (invariant 15).
    HUMAN = "human_reply"
    #: Vacation responder, ticket acknowledgement, mailbox rule. Does NOT stop
    #: the sequence, because nobody has actually read the message yet.
    AUTO = "auto_reply"
    #: Delivery status notification. Suppresses on a permanent failure.
    BOUNCE = "bounce"
    #: An explicit request to stop. Suppresses immediately and permanently.
    UNSUBSCRIBE = "unsubscribe_request"
    #: "This is spam." The most serious signal there is.
    COMPLAINT = "complaint"


@dataclass(frozen=True, slots=True)
class InboundMessage:
    """One arriving email, however it was collected."""

    from_email: str
    subject: str
    body_text: str
    headers: dict[str, str] = field(default_factory=dict)
    #: Present on a DSN: multipart/report; report-type=delivery-status.
    content_type: str = "text/plain"
    #: The Message-ID this is a reply to, when threading is available.
    in_reply_to: str | None = None

    def header(self, name: str) -> str:
        """Case-insensitive header lookup; senders vary the casing freely."""
        target = name.lower()
        for key, value in self.headers.items():
            if key.lower() == target:
                return value or ""
        return ""


@dataclass(frozen=True, slots=True)
class ReplyClassification:
    kind: ReplyKind
    #: Which rules fired. Recorded so a misclassification can be diagnosed
    #: rather than argued about.
    signals: tuple[str, ...] = ()
    detail: str | None = None

    @property
    def stops_the_sequence(self) -> bool:
        """Whether outreach to this lead must stop.

        An auto-reply does not qualify: no human has read anything yet.
        """
        return self.kind in (
            ReplyKind.HUMAN,
            ReplyKind.UNSUBSCRIBE,
            ReplyKind.COMPLAINT,
        )

    @property
    def requires_suppression(self) -> bool:
        """Whether the address must never be written to again."""
        return self.kind in (ReplyKind.UNSUBSCRIBE, ReplyKind.COMPLAINT)


# --------------------------------------------------------------------------
# Detectors
# --------------------------------------------------------------------------

#: RFC 3834 and the de-facto conventions around it. A message carrying any of
#: these was generated by a machine, whatever its subject line says.
_AUTO_HEADERS: tuple[tuple[str, re.Pattern[str]], ...] = (
    # RFC 3834: "auto-replied", "auto-generated", "auto-notified".
    ("auto-submitted", re.compile(r"auto-(replied|generated|notified)", re.I)),
    ("x-autoreply", re.compile(r".+")),
    ("x-autorespond", re.compile(r".+")),
    ("x-auto-response-suppress", re.compile(r".+")),
    ("precedence", re.compile(r"^\s*(auto_reply|bulk|junk|list)\s*$", re.I)),
    ("x-precedence", re.compile(r"^\s*(auto_reply|bulk|junk)\s*$", re.I)),
)

_AUTO_SUBJECTS = (
    re.compile(
        r"\b(out of (the )?office|automatic reply|auto[- ]?reply|autoreply|"
        r"away from (my|the) (desk|office)|on (annual |parental |maternity )?leave|"
        r"vacation (response|reply)|abwesenheit|réponse automatique)\b",
        re.I,
    ),
    re.compile(
        r"\b(ticket|case|request)\s*#?\s*\d+\s*(has been|was)\s*(created|received)\b",
        re.I,
    ),
    re.compile(r"\bthank you for (contacting|your (email|message|enquiry))\b", re.I),
)

#: A bounce announces itself in the envelope long before the body.
_BOUNCE_SENDERS = re.compile(
    r"^(mailer-daemon|postmaster|mail delivery (subsystem|system)|"
    r"no-?reply.*bounce)",
    re.I,
)

_BOUNCE_SUBJECTS = (
    re.compile(
        r"\b(undeliverable|delivery (status notification|has failed|failure)|"
        r"returned mail|mail delivery failed|message not delivered|"
        r"failure notice)\b",
        re.I,
    ),
)

#: Permanent failure language in a DSN body. 5.x.x is the RFC 3463 class for
#: "do not retry"; 4.x.x is temporary and must NOT suppress.
_HARD_BOUNCE_BODY = (
    re.compile(r"\b5\.\d{1,3}\.\d{1,3}\b"),
    re.compile(
        r"\b(user unknown|no such (user|mailbox|recipient)|"
        r"recipient address rejected|mailbox (unavailable|not found)|"
        r"address does not exist|account (has been )?(disabled|closed))\b",
        re.I,
    ),
)

_UNSUBSCRIBE = (
    re.compile(
        r"\b(unsubscribe|remove me|take me off|opt[- ]?out|stop (emailing|contacting|"
        r"messaging) me|do not (contact|email) me( again)?|"
        r"delete my (data|details|information))\b",
        re.I,
    ),
)

_COMPLAINT = (
    re.compile(
        r"\b(this is spam|reporting (this|you) (as|for) spam|marked as spam|"
        r"spam complaint|report(ing)? (this )?to (the )?ico|gdpr (breach|violation)|"
        r"i did not (consent|sign up|opt in))\b",
        re.I,
    ),
)


def classify_reply(message: InboundMessage) -> ReplyClassification:
    """Decide what an inbound message means.

    Order is deliberate and is the substance of this function:

    1. **Complaint** first -- it outranks everything, including an auto-reply
       header, because a complaint inside an automated wrapper is still a
       complaint.
    2. **Unsubscribe** next, for the same reason: a person asking to be left
       alone must be obeyed even if their mail system stamped the message.
    3. **Bounce**, which is machine-to-machine and never a human intent.
    4. **Auto-reply**, headers before wording.
    5. Otherwise a human wrote it.
    """
    signals: list[str] = []
    subject = message.subject or ""
    body = message.body_text or ""
    haystack = f"{subject}\n{body}"

    # ---- 1. complaint ------------------------------------------------------
    if _any(_COMPLAINT, haystack):
        signals.append("complaint_language")
        return ReplyClassification(
            ReplyKind.COMPLAINT,
            tuple(signals),
            "recipient reported this as spam or unsolicited",
        )

    # ---- 2. explicit opt-out ----------------------------------------------
    # Checked before the auto-reply rules on purpose: an out-of-office that
    # also says "and please remove me" is an opt-out, and obeying the header
    # instead of the sentence would ignore a direct request.
    if _any(_UNSUBSCRIBE, haystack):
        signals.append("unsubscribe_language")
        return ReplyClassification(
            ReplyKind.UNSUBSCRIBE, tuple(signals), "recipient asked not to be contacted"
        )

    # ---- 3. bounce ---------------------------------------------------------
    is_dsn = "report-type=delivery-status" in (message.content_type or "").lower()
    from_matches = bool(_BOUNCE_SENDERS.match((message.from_email or "").strip()))
    subject_matches = _any(_BOUNCE_SUBJECTS, subject)
    if is_dsn or from_matches or subject_matches:
        for name, marker in (
            ("dsn_content_type", is_dsn),
            ("daemon_sender", from_matches),
            ("bounce_subject", subject_matches),
        ):
            if marker:
                signals.append(name)
        hard = _any(_HARD_BOUNCE_BODY, body)
        if hard:
            signals.append("permanent_failure_code")
        return ReplyClassification(
            ReplyKind.BOUNCE,
            tuple(signals),
            "permanent delivery failure" if hard else "delivery failure, retryable",
        )

    # ---- 4. auto-reply -----------------------------------------------------
    for name, pattern in _AUTO_HEADERS:
        value = message.header(name)
        if value and pattern.search(value):
            signals.append(f"header:{name}")
            return ReplyClassification(
                ReplyKind.AUTO,
                tuple(signals),
                f"{name} indicates an automatic response; the sequence continues",
            )

    if _any(_AUTO_SUBJECTS, subject):
        signals.append("auto_reply_subject")
        return ReplyClassification(
            ReplyKind.AUTO,
            tuple(signals),
            "subject matches an automatic responder; the sequence continues",
        )

    # ---- 5. a person wrote back -------------------------------------------
    signals.append("no_automation_markers")
    return ReplyClassification(
        ReplyKind.HUMAN, tuple(signals), "treated as a human reply; outreach stops"
    )


def is_hard_bounce(classification: ReplyClassification) -> bool:
    """Whether a bounce is permanent and must suppress the address.

    A 4.x.x soft bounce -- full mailbox, greylisting -- must not: the address
    is fine and will accept mail later.
    """
    return (
        classification.kind is ReplyKind.BOUNCE
        and "permanent_failure_code" in classification.signals
    )


def _any(patterns: tuple[re.Pattern[str], ...], text: str) -> bool:
    return any(p.search(text) for p in patterns)


__all__ = [
    "InboundMessage",
    "ReplyClassification",
    "ReplyKind",
    "classify_reply",
    "is_hard_bounce",
]
